module.exports = {
  plugins: [
    'gatsby-plugin-postcss',
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/`,
        createLinkInHead: true,
      },
    },
  ],
  siteMetadata: {
    siteUrl: `https://saasbillinghub.com`,
    site: {
      org: 'Saas Billing Hub',
      niche: 'Saas Billing',
      published: new Date('2024-07-01').toISOString(),
      modified: new Date().toISOString(),
      domain: 'https://saasbillinghub.com',
      logo: '/logo.svg',
      favicon: '/favicon.ico',
      metaImage: '/meta.png',
      title: 'Saas Billing Hub',
      intro: 'Discover and compare features, pricing, and alternatives of top SaaS billing platforms. Your ultimate guide to finding the perfect billing solution.',
      adjectives: ['Best', 'Top',],
      formats: ['platforms', 'products', 'tools'],
      demographics: ['fintech', 'ecommerce'],
    },
    products: [
      {
        "name": "Chargebee",
        "logo": "https://example.com/logos/chargebee.png",
        "intro": "Chargebee is a scalable subscription management platform suitable for both startups and enterprises.",
        "conclusion": "Chargebee is ideal for businesses looking for flexible and comprehensive billing solutions.",
        "url": "https://www.chargebee.com",
        "affiliateUrl": "https://www.chargebee.com?ref=saasbillinghub",
        "image": "/chargebee.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Hosted Invoice Pages",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "$249/month", "b": "Up to $600K annual revenue" },
          { "a": "$549/month", "b": "Up to $900K annual revenue" },
          { "a": "Custom", "b": "Talk to sales for enterprise plans." }
        ]
      },
      {
        "name": "Recurly",
        "logo": "https://example.com/logos/recurly.png",
        "intro": "Recurly provides enterprise-class subscription billing management for thousands of businesses worldwide.",
        "conclusion": "Recurly is best suited for companies needing a robust and reliable billing platform.",
        "url": "https://www.recurly.com",
        "affiliateUrl": "https://www.recurly.com?ref=saasbillinghub",
        "image": "/recurly.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Hosted Invoice Pages",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "$199/month + 0.9% of revenue", "b": "" },
          { "a": "Custom", "b": "Talk to sales for enterprise plans." }
        ]
      },
      {
        "name": "Zuora",
        "logo": "https://example.com/logos/zuora.png",
        "intro": "Zuora is the leading subscription management platform for businesses of all sizes.",
        "conclusion": "Zuora is perfect for companies seeking a comprehensive subscription billing and revenue management solution.",
        "url": "https://www.zuora.com",
        "affiliateUrl": "https://www.zuora.com?ref=saasbillinghub",
        "image": "/zuora.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Hosted Invoice Pages",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "Request for details", "b": "" }
        ]
      },
      {
        "name": "Stripe",
        "logo": "https://example.com/logos/stripe.png",
        "intro": "Stripe Billing is a powerful billing platform built for modern businesses.",
        "conclusion": "Stripe Billing is ideal for companies looking for seamless integration with Stripe’s payment processing.",
        "url": "https://stripe.com/billing",
        "affiliateUrl": "https://stripe.com/billing?ref=saasbillinghub",
        "image": "/stripe.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Hosted Invoice Pages",
          "Integration with Stripe Payments",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "0.5% of recurring charges + transaction fees", "b": "" }
        ]
      },
      {
        "name": "Billsby",
        "logo": "https://example.com/logos/billsby.png",
        "intro": "Billsby is a comprehensive subscription management and billing platform.",
        "conclusion": "Billsby is suitable for businesses looking for straightforward subscription billing solutions.",
        "url": "https://www.billsby.com",
        "affiliateUrl": "https://www.billsby.com?ref=saasbillinghub",
        "image": "/billsby.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "$75/month", "b": "Up to $100K monthly revenue" },
          { "a": "$150/month", "b": "Up to $500K monthly revenue" },
          { "a": "$225/month", "b": "Up to $1M monthly revenue" }
        ]
      },
      {
        "name": "Paddle",
        "logo": "https://example.com/logos/paddle.png",
        "intro": "Paddle offers a complete solution for SaaS billing, checkout, and compliance.",
        "conclusion": "Paddle is ideal for SaaS businesses looking for an all-in-one billing platform.",
        "url": "https://www.paddle.com",
        "affiliateUrl": "https://www.paddle.com?ref=saasbillinghub",
        "image": "/paddle.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "5% + $0.50 per transaction", "b": "" }
        ]
      },
      {
        "name": "Rebilly",
        "logo": "https://example.com/logos/rebilly.png",
        "intro": "Rebilly is a comprehensive billing and payment orchestration platform.",
        "conclusion": "Rebilly is perfect for businesses seeking a highly customizable billing solution.",
        "url": "https://www.rebilly.com",
        "affiliateUrl": "https://www.rebilly.com?ref=saasbillinghub",
        "image": "/rebilly.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "$149/month", "b": "" },
          { "a": "$249/month", "b": "" },
          { "a": "$549/month", "b": "" },
          { "a": "Custom", "b": "Talk to sales for enterprise plans." }
        ]
      },
      {
        "name": "FastSpring",
        "logo": "https://example.com/logos/fastspring.png",
        "intro": "FastSpring is an all-in-one payment platform for software, SaaS, and digital products.",
        "conclusion": "FastSpring is best for businesses looking for a comprehensive e-commerce and billing solution.",
        "url": "https://www.fastspring.com",
        "affiliateUrl": "https://www.fastspring.com?ref=saasbillinghub",
        "image": "/fastspring.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "8.9% per transaction", "b": "Suitable for lower transaction volumes" },
          { "a": "5.9% + $0.95 per transaction", "b": "Better for higher transaction volumes" }
        ]
      },
      {
        "name": "MoonClerk",
        "logo": "https://example.com/logos/moonclerk.png",
        "intro": "MoonClerk offers a flexible, easy-to-use recurring payment system.",
        "conclusion": "MoonClerk is ideal for small businesses and nonprofits needing simple payment solutions.",
        "url": "https://www.moonclerk.com",
        "affiliateUrl": "https://www.moonclerk.com?ref=saasbillinghub",
        "image": "/moonclerk.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "$18/month", "b": "Up to $2000 in transactions" },
          { "a": "Scales with transaction volume", "b": "" }
        ]
      },
      {
        "name": "Chargemonk",
        "logo": "https://example.com/logos/chargemonk.png",
        "intro": "Chargemonk offers an all-in-one subscription billing and revenue management platform.",
        "conclusion": "Chargemonk is great for businesses seeking a flexible and scalable billing solution.",
        "url": "https://www.chargemonk.com",
        "affiliateUrl": "https://www.chargemonk.com?ref=saasbillinghub",
        "image": "/chargemonk.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "Request for details", "b": "" }
        ]
      },
      {
        "name": "PayWhirl",
        "logo": "https://example.com/logos/paywhirl.png",
        "intro": "PayWhirl provides easy-to-use subscription billing and payment solutions.",
        "conclusion": "PayWhirl is ideal for businesses seeking simple and efficient subscription management.",
        "url": "https://www.paywhirl.com",
        "affiliateUrl": "https://www.paywhirl.com?ref=saasbillinghub",
        "image": "/paywhirl.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "$49/month", "b": "" },
          { "a": "$149/month", "b": "" },
          { "a": "$249/month", "b": "" },
          { "a": "$549/month", "b": "" }
        ]
      },
      {
        "name": "Maxio",
        "logo": "https://example.com/logos/maxio.png",
        "intro": "Maxio provides a powerful billing and subscription management platform for SaaS companies.",
        "conclusion": "Maxio is best for SaaS companies looking for a flexible and comprehensive billing solution.",
        "url": "https://www.maxio.com",
        "affiliateUrl": "https://www.maxio.com?ref=saasbillinghub",
        "image": "/maxio.png",
        "features": [
          "Billing Automation",
          "Subscription Management",
          "API Access",
          "Multiple Payment Gateways",
          "Advanced Analytics",
          "Revenue Recognition",
          "Dunning Management",
          "Customizable Invoicing",
          "Plan Customization",
          "Multi-currency Support",
          "Tax Management",
          "PCI Compliance",
          "Customer Management",
          "Hosted Payment Pages",
          "Metered Billing",
          "Customizable Pricing Models",
          "Fraud Prevention",
          "Email Notifications",
          "Payment Retry Logic",
          "Hosted Checkout Pages",
          "Custom Domain",
          "Customer Portal",
          "Flexible Billing Frequencies",
          "Quote-to-Cash Process",
          "Product Catalog Management",
          "Invoice Scheduling",
          "Multi-entity Support",
          "Payment Method Management",
          "Contract Lifecycle Management",
          "Invoice Templates",
          "Proration",
          "Trial Management",
          "Payment Reconciliation",
          "Real-time Data Synchronization",
          "Usage-Based Pricing",
          "Financial Reporting",
          "Fraud Detection",
          "Email Invoicing",
          "Subscription Lifecycle Management",
          "Coupon and Discounts",
          "Multi-language Support",
          "Revenue Forecasting",
          "Invoice History",
          "Integrations with CRM and ERP"
        ],
        "pricingStructure": ["Price", "Details"],
        "pricingData": [
          { "a": "Request for details", "b": "" }
        ]
      }
    ]
  },
}
